Please write a travel itinerary according to the following conditions.
spotname이 영문명이여도 일정에 포함시켜줘.
touristspots에서 할 활동도 추천해줘.
날짜별,시간별로 지역, 활동이 들어간 일정을 작성해줘.
하루에 여러 touristspot을 가도 괜찮아.
일차별 일정에 대한 요약도 구체적으로 작성해줘.
budget은 원화 기준이고 고려해서 작성해줘.

지시사항:
- day는 시작일부터 하루씩
- summary는 day 동안의 일정을 3줄 정도로 요약해서 작성해줘.
- spots 안에 spot을 작성해줘,
- spot에서 summary는 간단한 문장으로 요약해서 작성해줘.
- spot에서 time은 시간별로 일정을 작성해줘야 해.
- spot에서 touristSpot은 time에 가는 touristSpot이야.
- spot에서 activity는 touristSpot에서 할 수 있는 활동을 작성해.

조건 :
- touristspots : {touristspots}
- startDate : {startDate}
- endDate : {endDate}
- budget : {budget}


